---

- name: enable firewalld service
  service: name=firewalld enabled=true state=started

- name: start firewalld
  service: name=firewalld state=restarted enabled=true

- name: Enable firewall Virtual Redundancy Router Protocol
  shell: firewall-cmd --permanent  --add-port=80/tcp --add-port=443/tcp  --add-port=22/tcp --add-port=6443/tcp  --add-port=2379/tcp  --add-port=2380/tcp --add-port=10250/tcp  --add-port=10259/tcp  --add-port=10257/tcp && firewall-cmd --reload

- name: Enable firewall Virtual Redundancy Router Protocol
  shell: firewall-cmd --direct --permanent --add-rule ipv4 filter INPUT 0 \ --in-interface eno1 --destination 224.0.0.18 --protocol vrrp -j ACCEPT

- name: Enable firewall Virtual Redundancy Router Protocol
  shell: firewall-cmd --direct --permanent --add-rule ipv4 filter OUTPUT 0 \ --out-interface eno1 --destination 224.0.0.18 --protocol vrrp -j ACCEPT

- name: Reload firewall
  shell: firewall-cmd --reload

- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_packages }}"

- name: Copy sysctl.conf configuration file
  template:
   src: sysctl.conf.j2
   dest: /etc/sysctl.conf
   mode: 0644

- name: Copy haproxy.cfg configuration file
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
   mode: 0644

- name: Ensure SELinux is in disabled mode
  lineinfile:
    dest: /etc/selinux/config
    backup: yes
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: enable haproxy service
  service: name=haproxy enabled=true state=started

- name: start haproxy
  service: name=haproxy state=restarted enabled=true